### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by laurivers** [kishikawakatsumi/Mozc-for-iOS#3]
I compile this lib on Xcode 6.3 OS X 10.10.3,
when I touch a hiragana, it crash easily. Also the demo(https://github.com/kishikawakatsumi/JapaneseKeyboardKit)

**Comment by namera** [comment]
Me too.

**Comment by ryonandesukedo** [comment]
Me too.

**Comment by kishikawakatsumi** [comment]
Closing too old, no details
